project:
  type: website

website:
  title: "new-site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: custom.scss
    toc: true

editor: visual

